// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息ID
type ID int32

const (
	ID_MSG_BEGIN     ID = 0
	ID_MSG_Connect   ID = 1   //连接(客户端发来第一个消息)
	ID_MSG_Heartbeat ID = 2   //心跳(服务端返回Connect成功之后每隔1秒发送一个心跳包)
	ID_MSG_JoinRoom  ID = 10  //进入
	ID_MSG_Progress  ID = 20  //进度
	ID_MSG_Ready     ID = 30  //准备
	ID_MSG_Start     ID = 40  //开始
	ID_MSG_Frame     ID = 50  //帧数据
	ID_MSG_Input     ID = 60  //输入
	ID_MSG_Result    ID = 70  //结果
	ID_MSG_Close     ID = 100 //房间关闭
	ID_MSG_END       ID = 255
)

// Enum value maps for ID.
var (
	ID_name = map[int32]string{
		0:   "MSG_BEGIN",
		1:   "MSG_Connect",
		2:   "MSG_Heartbeat",
		10:  "MSG_JoinRoom",
		20:  "MSG_Progress",
		30:  "MSG_Ready",
		40:  "MSG_Start",
		50:  "MSG_Frame",
		60:  "MSG_Input",
		70:  "MSG_Result",
		100: "MSG_Close",
		255: "MSG_END",
	}
	ID_value = map[string]int32{
		"MSG_BEGIN":     0,
		"MSG_Connect":   1,
		"MSG_Heartbeat": 2,
		"MSG_JoinRoom":  10,
		"MSG_Progress":  20,
		"MSG_Ready":     30,
		"MSG_Start":     40,
		"MSG_Frame":     50,
		"MSG_Input":     60,
		"MSG_Result":    70,
		"MSG_Close":     100,
		"MSG_END":       255,
	}
)

func (x ID) Enum() *ID {
	p := new(ID)
	*p = x
	return p
}

func (x ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ID) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (ID) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ID.Descriptor instead.
func (ID) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

// 错误码
type ERRORCODE int32

const (
	ERRORCODE_ERR_Ok        ERRORCODE = 0 //OK
	ERRORCODE_ERR_NoPlayer  ERRORCODE = 1 //没有这个玩家
	ERRORCODE_ERR_NoRoom    ERRORCODE = 2 //没有房间
	ERRORCODE_ERR_RoomState ERRORCODE = 3 //房间状态不正确
	ERRORCODE_ERR_Token     ERRORCODE = 4 //Token验证失败
)

// Enum value maps for ERRORCODE.
var (
	ERRORCODE_name = map[int32]string{
		0: "ERR_Ok",
		1: "ERR_NoPlayer",
		2: "ERR_NoRoom",
		3: "ERR_RoomState",
		4: "ERR_Token",
	}
	ERRORCODE_value = map[string]int32{
		"ERR_Ok":        0,
		"ERR_NoPlayer":  1,
		"ERR_NoRoom":    2,
		"ERR_RoomState": 3,
		"ERR_Token":     4,
	}
)

func (x ERRORCODE) Enum() *ERRORCODE {
	p := new(ERRORCODE)
	*p = x
	return p
}

func (x ERRORCODE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ERRORCODE) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[1].Descriptor()
}

func (ERRORCODE) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[1]
}

func (x ERRORCODE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ERRORCODE.Descriptor instead.
func (ERRORCODE) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

// 客户端发来的第一个消息
type C2S_ConnectMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerID      *uint64                `protobuf:"varint,1,opt,name=playerID,proto3,oneof" json:"playerID,omitempty"` //唯一ID
	BattleID      *uint64                `protobuf:"varint,2,opt,name=battleID,proto3,oneof" json:"battleID,omitempty"` //战斗ID
	Token         *string                `protobuf:"bytes,10,opt,name=token,proto3,oneof" json:"token,omitempty"`       //令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_ConnectMsg) Reset() {
	*x = C2S_ConnectMsg{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_ConnectMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_ConnectMsg) ProtoMessage() {}

func (x *C2S_ConnectMsg) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_ConnectMsg.ProtoReflect.Descriptor instead.
func (*C2S_ConnectMsg) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *C2S_ConnectMsg) GetPlayerID() uint64 {
	if x != nil && x.PlayerID != nil {
		return *x.PlayerID
	}
	return 0
}

func (x *C2S_ConnectMsg) GetBattleID() uint64 {
	if x != nil && x.BattleID != nil {
		return *x.BattleID
	}
	return 0
}

func (x *C2S_ConnectMsg) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

// 服务端返回连接结果
type S2C_ConnectMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     *ERRORCODE             `protobuf:"varint,1,opt,name=errorCode,proto3,enum=pb.ERRORCODE,oneof" json:"errorCode,omitempty"` //错误码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_ConnectMsg) Reset() {
	*x = S2C_ConnectMsg{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_ConnectMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_ConnectMsg) ProtoMessage() {}

func (x *S2C_ConnectMsg) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_ConnectMsg.ProtoReflect.Descriptor instead.
func (*S2C_ConnectMsg) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *S2C_ConnectMsg) GetErrorCode() ERRORCODE {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return ERRORCODE_ERR_Ok
}

// 服务端返回进入房间消息
type S2C_JoinRoomMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roomseatid    *int32                 `protobuf:"varint,1,opt,name=roomseatid,proto3,oneof" json:"roomseatid,omitempty"` //自己的位置索引id(1~N)
	Others        []uint64               `protobuf:"varint,2,rep,packed,name=others,proto3" json:"others,omitempty"`        //其他人的id
	Pros          []int32                `protobuf:"varint,3,rep,packed,name=pros,proto3" json:"pros,omitempty"`            //其他人的进度
	RandomSeed    *int32                 `protobuf:"varint,4,opt,name=randomSeed,proto3,oneof" json:"randomSeed,omitempty"` //随机种子
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_JoinRoomMsg) Reset() {
	*x = S2C_JoinRoomMsg{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_JoinRoomMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_JoinRoomMsg) ProtoMessage() {}

func (x *S2C_JoinRoomMsg) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_JoinRoomMsg.ProtoReflect.Descriptor instead.
func (*S2C_JoinRoomMsg) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *S2C_JoinRoomMsg) GetRoomseatid() int32 {
	if x != nil && x.Roomseatid != nil {
		return *x.Roomseatid
	}
	return 0
}

func (x *S2C_JoinRoomMsg) GetOthers() []uint64 {
	if x != nil {
		return x.Others
	}
	return nil
}

func (x *S2C_JoinRoomMsg) GetPros() []int32 {
	if x != nil {
		return x.Pros
	}
	return nil
}

func (x *S2C_JoinRoomMsg) GetRandomSeed() int32 {
	if x != nil && x.RandomSeed != nil {
		return *x.RandomSeed
	}
	return 0
}

// 服务端广播开始游戏消息
type S2C_StartMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeStamp     *int64                 `protobuf:"varint,1,opt,name=timeStamp,proto3,oneof" json:"timeStamp,omitempty"` //同步时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_StartMsg) Reset() {
	*x = S2C_StartMsg{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_StartMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_StartMsg) ProtoMessage() {}

func (x *S2C_StartMsg) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_StartMsg.ProtoReflect.Descriptor instead.
func (*S2C_StartMsg) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *S2C_StartMsg) GetTimeStamp() int64 {
	if x != nil && x.TimeStamp != nil {
		return *x.TimeStamp
	}
	return 0
}

// 读条进度
type C2S_ProgressMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pro           *int32                 `protobuf:"varint,1,opt,name=pro,proto3,oneof" json:"pro,omitempty"` //进度值0~100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_ProgressMsg) Reset() {
	*x = C2S_ProgressMsg{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_ProgressMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_ProgressMsg) ProtoMessage() {}

func (x *C2S_ProgressMsg) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_ProgressMsg.ProtoReflect.Descriptor instead.
func (*C2S_ProgressMsg) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *C2S_ProgressMsg) GetPro() int32 {
	if x != nil && x.Pro != nil {
		return *x.Pro
	}
	return 0
}

// 读条进度
type S2C_ProgressMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint64                `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`   //id
	Pro           *int32                 `protobuf:"varint,2,opt,name=pro,proto3,oneof" json:"pro,omitempty"` //进度值0~100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_ProgressMsg) Reset() {
	*x = S2C_ProgressMsg{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_ProgressMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_ProgressMsg) ProtoMessage() {}

func (x *S2C_ProgressMsg) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_ProgressMsg.ProtoReflect.Descriptor instead.
func (*S2C_ProgressMsg) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *S2C_ProgressMsg) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *S2C_ProgressMsg) GetPro() int32 {
	if x != nil && x.Pro != nil {
		return *x.Pro
	}
	return 0
}

// 操作输入消息
type C2S_InputMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *PBInput               `protobuf:"bytes,1,opt,name=input,proto3,oneof" json:"input,omitempty"`      //操作id
	Event         *PBEvent               `protobuf:"bytes,2,opt,name=event,proto3,oneof" json:"event,omitempty"`      //事件
	FrameID       *uint32                `protobuf:"varint,3,opt,name=frameID,proto3,oneof" json:"frameID,omitempty"` //帧ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_InputMsg) Reset() {
	*x = C2S_InputMsg{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_InputMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_InputMsg) ProtoMessage() {}

func (x *C2S_InputMsg) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_InputMsg.ProtoReflect.Descriptor instead.
func (*C2S_InputMsg) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *C2S_InputMsg) GetInput() *PBInput {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *C2S_InputMsg) GetEvent() *PBEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *C2S_InputMsg) GetFrameID() uint32 {
	if x != nil && x.FrameID != nil {
		return *x.FrameID
	}
	return 0
}

// 上一帧客户端没有输入 重复输入
type PBInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           *int32                 `protobuf:"varint,1,opt,name=sid,proto3,oneof" json:"sid,omitempty"` //操作id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBInput) Reset() {
	*x = PBInput{}
	mi := &file_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBInput) ProtoMessage() {}

func (x *PBInput) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBInput.ProtoReflect.Descriptor instead.
func (*PBInput) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *PBInput) GetSid() int32 {
	if x != nil && x.Sid != nil {
		return *x.Sid
	}
	return 0
}

// 上一帧客户端没有输入 事件归零
type PBEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       *int32                 `protobuf:"varint,1,opt,name=eventId,proto3,oneof" json:"eventId,omitempty"` //操作id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBEvent) Reset() {
	*x = PBEvent{}
	mi := &file_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBEvent) ProtoMessage() {}

func (x *PBEvent) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBEvent.ProtoReflect.Descriptor instead.
func (*PBEvent) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8}
}

func (x *PBEvent) GetEventId() int32 {
	if x != nil && x.EventId != nil {
		return *x.EventId
	}
	return 0
}

// 帧存储操作输入
type InputData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint64                `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`                 //id
	Input         *PBInput               `protobuf:"bytes,2,opt,name=input,proto3,oneof" json:"input,omitempty"`            //操作id
	Event         *PBEvent               `protobuf:"bytes,3,opt,name=event,proto3,oneof" json:"event,omitempty"`            //事件
	Roomseatid    *int32                 `protobuf:"varint,4,opt,name=roomseatid,proto3,oneof" json:"roomseatid,omitempty"` //操作者的位置索引id(1~N)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputData) Reset() {
	*x = InputData{}
	mi := &file_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputData) ProtoMessage() {}

func (x *InputData) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputData.ProtoReflect.Descriptor instead.
func (*InputData) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{9}
}

func (x *InputData) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *InputData) GetInput() *PBInput {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *InputData) GetEvent() *PBEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *InputData) GetRoomseatid() int32 {
	if x != nil && x.Roomseatid != nil {
		return *x.Roomseatid
	}
	return 0
}

// 帧数据
type FrameData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameID       *uint32                `protobuf:"varint,1,opt,name=frameID,proto3,oneof" json:"frameID,omitempty"` //帧ID
	Input         []*InputData           `protobuf:"bytes,2,rep,name=input,proto3" json:"input,omitempty"`            //操作输入
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameData) Reset() {
	*x = FrameData{}
	mi := &file_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameData) ProtoMessage() {}

func (x *FrameData) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameData.ProtoReflect.Descriptor instead.
func (*FrameData) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{10}
}

func (x *FrameData) GetFrameID() uint32 {
	if x != nil && x.FrameID != nil {
		return *x.FrameID
	}
	return 0
}

func (x *FrameData) GetInput() []*InputData {
	if x != nil {
		return x.Input
	}
	return nil
}

// 广播帧消息
type S2C_FrameMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frames        []*FrameData           `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"` //帧数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_FrameMsg) Reset() {
	*x = S2C_FrameMsg{}
	mi := &file_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_FrameMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_FrameMsg) ProtoMessage() {}

func (x *S2C_FrameMsg) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_FrameMsg.ProtoReflect.Descriptor instead.
func (*S2C_FrameMsg) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{11}
}

func (x *S2C_FrameMsg) GetFrames() []*FrameData {
	if x != nil {
		return x.Frames
	}
	return nil
}

// 结果消息
type C2S_ResultMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinnerID      *uint64                `protobuf:"varint,1,opt,name=winnerID,proto3,oneof" json:"winnerID,omitempty"` //胜利者ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_ResultMsg) Reset() {
	*x = C2S_ResultMsg{}
	mi := &file_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_ResultMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_ResultMsg) ProtoMessage() {}

func (x *C2S_ResultMsg) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_ResultMsg.ProtoReflect.Descriptor instead.
func (*C2S_ResultMsg) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{12}
}

func (x *C2S_ResultMsg) GetWinnerID() uint64 {
	if x != nil && x.WinnerID != nil {
		return *x.WinnerID
	}
	return 0
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\x02pb\"\x91\x01\n" +
	"\x0eC2S_ConnectMsg\x12\x1f\n" +
	"\bplayerID\x18\x01 \x01(\x04H\x00R\bplayerID\x88\x01\x01\x12\x1f\n" +
	"\bbattleID\x18\x02 \x01(\x04H\x01R\bbattleID\x88\x01\x01\x12\x19\n" +
	"\x05token\x18\n" +
	" \x01(\tH\x02R\x05token\x88\x01\x01B\v\n" +
	"\t_playerIDB\v\n" +
	"\t_battleIDB\b\n" +
	"\x06_token\"P\n" +
	"\x0eS2C_ConnectMsg\x120\n" +
	"\terrorCode\x18\x01 \x01(\x0e2\r.pb.ERRORCODEH\x00R\terrorCode\x88\x01\x01B\f\n" +
	"\n" +
	"_errorCode\"\xa5\x01\n" +
	"\x0fS2C_JoinRoomMsg\x12#\n" +
	"\n" +
	"roomseatid\x18\x01 \x01(\x05H\x00R\n" +
	"roomseatid\x88\x01\x01\x12\x16\n" +
	"\x06others\x18\x02 \x03(\x04R\x06others\x12\x12\n" +
	"\x04pros\x18\x03 \x03(\x05R\x04pros\x12#\n" +
	"\n" +
	"randomSeed\x18\x04 \x01(\x05H\x01R\n" +
	"randomSeed\x88\x01\x01B\r\n" +
	"\v_roomseatidB\r\n" +
	"\v_randomSeed\"?\n" +
	"\fS2C_StartMsg\x12!\n" +
	"\ttimeStamp\x18\x01 \x01(\x03H\x00R\ttimeStamp\x88\x01\x01B\f\n" +
	"\n" +
	"_timeStamp\"0\n" +
	"\x0fC2S_ProgressMsg\x12\x15\n" +
	"\x03pro\x18\x01 \x01(\x05H\x00R\x03pro\x88\x01\x01B\x06\n" +
	"\x04_pro\"L\n" +
	"\x0fS2C_ProgressMsg\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x04H\x00R\x02id\x88\x01\x01\x12\x15\n" +
	"\x03pro\x18\x02 \x01(\x05H\x01R\x03pro\x88\x01\x01B\x05\n" +
	"\x03_idB\x06\n" +
	"\x04_pro\"\x9d\x01\n" +
	"\fC2S_InputMsg\x12&\n" +
	"\x05input\x18\x01 \x01(\v2\v.pb.PBInputH\x00R\x05input\x88\x01\x01\x12&\n" +
	"\x05event\x18\x02 \x01(\v2\v.pb.PBEventH\x01R\x05event\x88\x01\x01\x12\x1d\n" +
	"\aframeID\x18\x03 \x01(\rH\x02R\aframeID\x88\x01\x01B\b\n" +
	"\x06_inputB\b\n" +
	"\x06_eventB\n" +
	"\n" +
	"\b_frameID\"(\n" +
	"\aPBInput\x12\x15\n" +
	"\x03sid\x18\x01 \x01(\x05H\x00R\x03sid\x88\x01\x01B\x06\n" +
	"\x04_sid\"4\n" +
	"\aPBEvent\x12\x1d\n" +
	"\aeventId\x18\x01 \x01(\x05H\x00R\aeventId\x88\x01\x01B\n" +
	"\n" +
	"\b_eventId\"\xbf\x01\n" +
	"\tInputData\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x04H\x00R\x02id\x88\x01\x01\x12&\n" +
	"\x05input\x18\x02 \x01(\v2\v.pb.PBInputH\x01R\x05input\x88\x01\x01\x12&\n" +
	"\x05event\x18\x03 \x01(\v2\v.pb.PBEventH\x02R\x05event\x88\x01\x01\x12#\n" +
	"\n" +
	"roomseatid\x18\x04 \x01(\x05H\x03R\n" +
	"roomseatid\x88\x01\x01B\x05\n" +
	"\x03_idB\b\n" +
	"\x06_inputB\b\n" +
	"\x06_eventB\r\n" +
	"\v_roomseatid\"[\n" +
	"\tFrameData\x12\x1d\n" +
	"\aframeID\x18\x01 \x01(\rH\x00R\aframeID\x88\x01\x01\x12#\n" +
	"\x05input\x18\x02 \x03(\v2\r.pb.InputDataR\x05inputB\n" +
	"\n" +
	"\b_frameID\"5\n" +
	"\fS2C_FrameMsg\x12%\n" +
	"\x06frames\x18\x01 \x03(\v2\r.pb.FrameDataR\x06frames\"=\n" +
	"\rC2S_ResultMsg\x12\x1f\n" +
	"\bwinnerID\x18\x01 \x01(\x04H\x00R\bwinnerID\x88\x01\x01B\v\n" +
	"\t_winnerID*\xc4\x01\n" +
	"\x02ID\x12\r\n" +
	"\tMSG_BEGIN\x10\x00\x12\x0f\n" +
	"\vMSG_Connect\x10\x01\x12\x11\n" +
	"\rMSG_Heartbeat\x10\x02\x12\x10\n" +
	"\fMSG_JoinRoom\x10\n" +
	"\x12\x10\n" +
	"\fMSG_Progress\x10\x14\x12\r\n" +
	"\tMSG_Ready\x10\x1e\x12\r\n" +
	"\tMSG_Start\x10(\x12\r\n" +
	"\tMSG_Frame\x102\x12\r\n" +
	"\tMSG_Input\x10<\x12\x0e\n" +
	"\n" +
	"MSG_Result\x10F\x12\r\n" +
	"\tMSG_Close\x10d\x12\f\n" +
	"\aMSG_END\x10\xff\x01*[\n" +
	"\tERRORCODE\x12\n" +
	"\n" +
	"\x06ERR_Ok\x10\x00\x12\x10\n" +
	"\fERR_NoPlayer\x10\x01\x12\x0e\n" +
	"\n" +
	"ERR_NoRoom\x10\x02\x12\x11\n" +
	"\rERR_RoomState\x10\x03\x12\r\n" +
	"\tERR_Token\x10\x04B-Z+github.com/byebyebruce/lockstepserver/pb;pbb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_message_proto_goTypes = []any{
	(ID)(0),                 // 0: pb.ID
	(ERRORCODE)(0),          // 1: pb.ERRORCODE
	(*C2S_ConnectMsg)(nil),  // 2: pb.C2S_ConnectMsg
	(*S2C_ConnectMsg)(nil),  // 3: pb.S2C_ConnectMsg
	(*S2C_JoinRoomMsg)(nil), // 4: pb.S2C_JoinRoomMsg
	(*S2C_StartMsg)(nil),    // 5: pb.S2C_StartMsg
	(*C2S_ProgressMsg)(nil), // 6: pb.C2S_ProgressMsg
	(*S2C_ProgressMsg)(nil), // 7: pb.S2C_ProgressMsg
	(*C2S_InputMsg)(nil),    // 8: pb.C2S_InputMsg
	(*PBInput)(nil),         // 9: pb.PBInput
	(*PBEvent)(nil),         // 10: pb.PBEvent
	(*InputData)(nil),       // 11: pb.InputData
	(*FrameData)(nil),       // 12: pb.FrameData
	(*S2C_FrameMsg)(nil),    // 13: pb.S2C_FrameMsg
	(*C2S_ResultMsg)(nil),   // 14: pb.C2S_ResultMsg
}
var file_message_proto_depIdxs = []int32{
	1,  // 0: pb.S2C_ConnectMsg.errorCode:type_name -> pb.ERRORCODE
	9,  // 1: pb.C2S_InputMsg.input:type_name -> pb.PBInput
	10, // 2: pb.C2S_InputMsg.event:type_name -> pb.PBEvent
	9,  // 3: pb.InputData.input:type_name -> pb.PBInput
	10, // 4: pb.InputData.event:type_name -> pb.PBEvent
	11, // 5: pb.FrameData.input:type_name -> pb.InputData
	12, // 6: pb.S2C_FrameMsg.frames:type_name -> pb.FrameData
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	file_message_proto_msgTypes[0].OneofWrappers = []any{}
	file_message_proto_msgTypes[1].OneofWrappers = []any{}
	file_message_proto_msgTypes[2].OneofWrappers = []any{}
	file_message_proto_msgTypes[3].OneofWrappers = []any{}
	file_message_proto_msgTypes[4].OneofWrappers = []any{}
	file_message_proto_msgTypes[5].OneofWrappers = []any{}
	file_message_proto_msgTypes[6].OneofWrappers = []any{}
	file_message_proto_msgTypes[7].OneofWrappers = []any{}
	file_message_proto_msgTypes[8].OneofWrappers = []any{}
	file_message_proto_msgTypes[9].OneofWrappers = []any{}
	file_message_proto_msgTypes[10].OneofWrappers = []any{}
	file_message_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
